# Macro file for the initialisation
# in interactive session

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 1

# Initialize kernel
#/machine/tableRef 60 120 78.5 cm
#/machine/isocenter 90 60 113.5 cm
/run/initialize

/phantom/install 0

# Source setting
#/control/execute source.mac

# Visualization setting
/control/execute vis.mac
