# Macro file for the initialisation
# in interactive session

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1

# Initialize kernel
/run/initialize

#/machine/removeDet
#/machine/removeGlass
/machine/useCurtain false
/machine/tableTrans 5 10 5 cm

#/phantom/data record.txt
#/phantom/frame 51

/beam/peak 80
/run/beamOn 100000
